### ISSUE TITLE
440 Hz tones at 0 hours UTC

### ISSUE THREAD

**Issue by jaybird110127** [kalafut/wwv#1]
The WWV/WWVH simulator incorrectly adds a 440 Hz tone during minute 2 of WWV, and presumably during minute 1 of WWVH, during the first UTC hour of each day (00:02/00:01 UTC). The real WWV/WWVH don't do this. Reference: NIST Special Publication 250-67

**Comment by kalafut** [comment]
Good catch. I remember reading that bit but it got lost among the myriad rules I was trying to keep straight during implementation. Happy to add handling for this case.

**Comment by kalafut** [comment]
@jaybird110127 Thanks. Change made and deployed.
