### ISSUE TITLE
Little Delay

### ISSUE THREAD

**Issue by Forecatfromthecatcrew** [kalafut/wwv#23]
Very Sync but it kind delay like it goes at the tone 20 hours 29 minutes UTC but I'ts 14:29

**Comment by Forecatfromthecatcrew** [comment]
also im in texas sooooo yeeeeeeeeah

**Comment by kalafut** [comment]
It your computer clock correct? It is simply based on that.

**Comment by Forecatfromthecatcrew** [comment]
Yes and it does on my phone and like it's 23:05 it says 5:05

**Comment by Forecatfromthecatcrew** [comment]
Unclose

**Comment by kalafut** [comment]
That sounds correct. UTC is 6 hours ahead of Texas.

**Comment by Forecatfromthecatcrew** [comment]
Thank I will try to remember that @kalafut

**Comment by Forecatfromthecatcrew** [comment]
But all I gotta say it a very safe app to use for school (I did) Thanks for the project

**Comment by kalafut** [comment]
@Forecatfromthecatcrew Interesting. How are you using it for school?

**Comment by Forecatfromthecatcrew** [comment]
> @Forecatfromthecatcrew Interesting. How are you using it for school?

How: I use the website and press play and it work as a charm like I'm boutta go to sleep with it
