### ISSUE TITLE
WWV / WWVH High-Def Identifier Samples

### ISSUE THREAD

**Issue by TS440S** [kalafut/wwv#31]
I've found a absolutely fantastic audio recording that has the best WWV identifiers I've ever heard. Credit goes to "
Signal Phantom" On youtube. The link to the videos are below.
https://www.youtube.com/watch?v=htkOwuoCy3M
https://www.youtube.com/watch?v=_orBKbUbi-Y

I've also included four files. Two are WWV, one with the 100hz heartbeat suppressed and one normal. Same for WWVH.

Sure beats the skype call audio quality, if you ever feel like using these for the actual website the author gave permission for anyone to use them, plus it's not like the author could copyright WWV.

[WWV Samples.zip](https://github.com/kalafut/wwv/files/10109715/WWV.Samples.zip)

**Comment by kalafut** [comment]
Good stuff, and should be easy to update. Lemme take a look.

**Comment by kalafut** [comment]
I just updated the site. Thanks again for taking the time to prepare the clips. Saved me a bunch of time.

**Comment by James-Andrasek** [comment]
Thanks so much for all who worked on this!
