### ISSUE TITLE
Volume is fixed

### ISSUE THREAD

**Issue by DJD119** [kalafut/wwv#8]
A volume slider would be very nice to have. At the volume I have set on Windows, the site is very loud relative to other things I do on my computer and in my browser. Currently I must turn my Windows volume down a lot to listen to the site, making everything else very quiet.

**Comment by kalafut** [comment]
That's not a bad idea!  My time is limited to work on this project, but this request is certainly on the easier side so we'll see.

Thanks.

**Comment by DJD119** [comment]
Thank you for the reply

**Comment by kalafut** [comment]
A volume control was just added by @sclickk and the site is live with their change. 🎉

**Comment by DJD119** [comment]
It is perfect, thank you
